Namespace(
    config=[Path_fsr(configs/cls/mbv2/filt_last1_r2.yaml, cwd=/home/infres/lnguyen-23/test/classification)],
    data=Namespace(
        batch_size=128,
        data_dir='data/cifar100',
        height=224,
        iid=False,
        name='cifar100',
        num_partitions=2,
        partition=1,
        shards_per_partition=2,
        train_shuffle=True,
        train_split=0.8,
        train_workers=12,
        usr_group=None,
        val_workers=12,
        width=224
    ),
    logger=Namespace(
        exp_name='filt_l1_r2_15.82',
        save_dir='runs/cls/mbv2/cifar100'
    ),
    model=Namespace(
        anneling_steps=50,
        backbone='mobilenet_v2',
        backbone_args={'in_channels': 3, 'output_stride': 32, 'weights': 'imagenet'},
        filter_cfgs={
            'filter_install': [
                {'path': 'backbone.features.18', 'radius': 2, 'type': 'ConvNormActivation'},
                {'path': 'backbone.features.17', 'radius': 2, 'type': 'InvertedResidual'},
                {'path': 'backbone.features.16', 'radius': 2, 'type': 'InvertedResidual'}
            ]
        },
        filter_late_install=True,
        freeze_cfgs=[
            {'path': 'backbone features [0]'},
            {'path': 'backbone features [1]'},
            {'path': 'backbone features [2]'},
            {'path': 'backbone features [3]'},
            {'path': 'backbone features [4]'},
            {'path': 'backbone features [5]'},
            {'path': 'backbone features [6]'},
            {'path': 'backbone features [7]'},
            {'path': 'backbone features [8]'},
            {'path': 'backbone features [9]'},
            {'path': 'backbone features [10]'},
            {'path': 'backbone features [11]'},
            {'path': 'backbone features [12]'},
            {'path': 'backbone features [13]'},
            {'path': 'backbone features [14]'},
            {'path': 'backbone features [15]'},
            {'path': 'backbone features [16]'},
            {'path': 'backbone features [17]'}
        ],
        init_lr_prod=0.25,
        learning_rate=0.05,
        load='pretrained_ckpts/mbv2/pretrain_15.82_cifar100/version_0/checkpoints/epoch=44-val-acc=0.812.ckpt',
        lr_warmup=0,
        momentum=0,
        num_classes=100,
        scheduler_interval='epoch',
        set_bn_eval=True,
        use_sgd=True,
        weight_decay=0.0001,
        with_grad_filter=True
    ),
    seed_everything=233,
    trainer=Namespace(
        accelerator=None,
        accumulate_grad_batches=None,
        amp_backend='native',
        amp_level=None,
        auto_lr_find=False,
        auto_scale_batch_size=False,
        auto_select_gpus=False,
        benchmark=None,
        callbacks=[
            Namespace(class_path='pytorch_lightning.callbacks.LearningRateMonitor', init_args=Namespace(log_momentum=False, logging_interval='epoch')),
            Namespace(class_path='pytorch_lightning.callbacks.GPUStatsMonitor', init_args=Namespace(fan_speed=True, gpu_utilization=True, inter_step_time=False, intra_step_time=False, memory_utilization=True, temperature=True)),
            Namespace(class_path='pytorch_lightning.callbacks.ModelCheckpoint', init_args=Namespace(auto_insert_metric_name=True, dirpath=None, every_n_epochs=None, every_n_train_steps=None, filename='{epoch:02d}-{val-acc:.3f}', mode='max', monitor='val-acc', save_last=True, save_on_train_epoch_end=None, save_top_k=2, save_weights_only=False, train_time_interval=None, verbose=False))
        ],
        check_val_every_n_epoch=1,
        checkpoint_callback=None,
        default_root_dir=None,
        detect_anomaly=False,
        deterministic=None,
        devices=None,
        enable_checkpointing=True,
        enable_model_summary=True,
        enable_progress_bar=True,
        fast_dev_run=False,
        flush_logs_every_n_steps=None,
        gpus=1,
        gradient_clip_algorithm=None,
        gradient_clip_val=2.0,
        ipus=None,
        limit_predict_batches=None,
        limit_test_batches=None,
        limit_train_batches=None,
        limit_val_batches=None,
        log_every_n_steps=5,
        log_gpu_memory=None,
        logger=True,
        max_epochs=50,
        max_steps=-1,
        max_time=None,
        min_epochs=None,
        min_steps=None,
        move_metrics_to_cpu=False,
        multiple_trainloader_mode='max_size_cycle',
        num_nodes=1,
        num_processes=None,
        num_sanity_val_steps=0,
        overfit_batches=0.0,
        plugins=None,
        precision=32,
        prepare_data_per_node=None,
        process_position=0,
        profiler=None,
        progress_bar_refresh_rate=None,
        reload_dataloaders_every_n_epochs=0,
        replace_sampler_ddp=True,
        resume_from_checkpoint=None,
        stochastic_weight_avg=False,
        strategy=None,
        sync_batchnorm=False,
        terminate_on_nan=None,
        tpu_cores=None,
        track_grad_norm=-1,
        val_check_interval=None,
        weights_save_path=None,
        weights_summary='top'
    )
)
