bash trung_scripts/mcunet/c10_mcunet_finetune_all.sh
bash trung_scripts/mcunet/c10_mcunet_finetune_all_r.sh
bash trung_scripts/mcunet/c10_mcunet_r2.sh
bash trung_scripts/mcunet/c10_mcunet_r4.sh
bash trung_scripts/mcunet/c10_mcunet_r7.sh
bash trung_scripts/mcunet/c100_mcunet_finetune_all.sh
bash trung_scripts/mcunet/c100_mcunet_finetune_all_r.sh
bash trung_scripts/mcunet/c100_mcunet_r2.sh
bash trung_scripts/mcunet/c100_mcunet_r4.sh
bash trung_scripts/mcunet/c100_mcunet_r7.sh